baseURL = "https://kaptanbajer.github.io/EN_GANG_TIL/"
title = "Dry notes"
description = "OKAY"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["KASPER BRUN"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/KaptajnBajer/EN_GANG_TIL"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

